# Generated by Django 5.2.1 on 2025-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('display_name', models.TextField(blank=True)),
                ('profile_image_url', models.URLField()),
                ('bio_text', models.TextField()),
                ('join_date', models.DateField()),
            ],
        ),
    ]
