# Generated by Django 5.2.1 on 2025-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_recipe_steps_delete_steprecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
